version: '3.1'

services:

  mariadb:
      container_name: "mariadb"
      image: mariadb:10
      restart: always
      ports:
        - 3307:3306
      volumes:
#        - "./mariadb/conf.d:/etc/mysql/conf.d"
#        - "./mariadb/data:/var/lib/mysql"
        - ./init-db/:/docker-entrypoint-initdb.d/
      environment:
        MARIADB_DATABASE: dev_maria
        MARIADB_USER: dev_maria_user
        MARIADB_PASSWORD: qwe123!@#
        MARIADB_ROOT_PASSWORD: qwe123!@#
