version: '3.1'

services:

    centos8:
        hostname: centos8
        container_name: centos8
        build:
            context: .
            dockerfile: ./centos8/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./centos8:/centos8
            - ./data:/data



#      centos8:
#        image: core01/centos
#        build: .
#        tty: true
#        ports:
#         - "80:80"
#         - "443:443"
#        volumes:
#         - /home/core01/dev/:/home/core01/
#         - ./nginx/:/etc/nginx/conf.d/
#         - ./php/:/etc/php-fpm.d/
#         - /sys/fs/cgroup:/sys/fs/cgroup:ro
#        privileged: true
#        extra_hosts:
#         - "aktas.dev:127.0.0.1"
